class CreateCalculationData < ActiveRecord::Migration[7.0]
  def change
    create_table :calculation_data do |t|
      t.decimal :investAmount
      t.integer :investPeriod
      t.decimal :growthPercentage
      t.decimal :annualContribution
      t.string :monthlyContribution
      t.decimal :year0
      t.decimal :year1
      t.decimal :year2
      t.decimal :year3
      t.decimal :year4
      t.decimal :year5
      t.decimal :year6
      t.decimal :year7
      t.decimal :year8
      t.decimal :year9
      t.decimal :year10
      t.decimal :year11
      t.decimal :year12
      t.decimal :year13
      t.decimal :year14
      t.decimal :year15
      t.decimal :year16
      t.decimal :year17
      t.decimal :year18
      t.decimal :year19
      t.decimal :year20
      t.decimal :year21
      t.decimal :year22
      t.decimal :year23
      t.decimal :year24
      t.decimal :year25
      t.decimal :year26
      t.decimal :year27
      t.decimal :year28
      t.decimal :year29
      t.decimal :year30
      t.decimal :year31
      t.decimal :year32
      t.decimal :year33
      t.decimal :year34
      t.decimal :year35
      t.decimal :year36
      t.decimal :year37
      t.decimal :year38
      t.decimal :year39
      t.decimal :year40
      t.decimal :year41
      t.decimal :year42
      t.decimal :year43
      t.decimal :year44
      t.decimal :year45
      t.decimal :year46
      t.decimal :year47
      t.decimal :year48
      t.decimal :year49
      t.decimal :year50
      t.decimal :year51
      t.decimal :year52
      t.decimal :year53
      t.decimal :year54
      t.decimal :year55
      t.decimal :year56
      t.decimal :year57
      t.decimal :year58
      t.decimal :year59
      t.decimal :year60
      t.decimal :year61
      t.decimal :year62
      t.decimal :year63
      t.decimal :year64
      t.decimal :year65
      t.decimal :year66
      t.decimal :year67
      t.decimal :year68
      t.decimal :year69
      t.decimal :year70
      t.decimal :year71
      t.decimal :year72
      t.decimal :year73
      t.decimal :year74
      t.decimal :year75
      t.decimal :year76
      t.decimal :year77
      t.decimal :year78
      t.decimal :year79
      t.decimal :year80
      t.decimal :year81
      t.decimal :year82
      t.decimal :year83
      t.decimal :year84
      t.decimal :year85
      t.decimal :year86
      t.decimal :year87
      t.decimal :year88
      t.decimal :year89
      t.decimal :year90
      t.decimal :year91
      t.decimal :year92
      t.decimal :year93
      t.decimal :year94
      t.decimal :year95
      t.decimal :year96
      t.decimal :year97
      t.decimal :year98
      t.decimal :year99
      t.decimal :year100

      t.timestamps
    end
  end
end
